name: smart_consulta
description: SmartConsulta - template funcional
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.4.0
  table_calendar: ^3.0.11
  go_router: ^7.0.1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^19.5.0

firebase_core: ^3.0.0
firebase_messaging: ^15.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/SmartConsulta_Logo.png
