name: smart_consulta
description: SmartConsulta - template funcional
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.4.0
  table_calendar: ^3.0.11
  go_router: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/SmartConsulta_Logo.png
